export default [
  [
    { title: '💀', subTitle: '', name: 'esc', keyCode: 27 },
    { title: '1', subTitle: '!', keyCode: 49 },
    { title: '2', subTitle: '@', keyCode: 50 },
    { title: '3', subTitle: '#', keyCode: 51 },
    { title: '4', subTitle: '$', keyCode: 52 },
    { title: '5', subTitle: '%', keyCode: 53 },
    { title: '6', subTitle: '^', keyCode: 54 },
    { title: '7', subTitle: '&', keyCode: 55 },
    { title: '8', subTitle: '*', keyCode: 56 },
    { title: '9', subTitle: '(', keyCode: 57 },
    { title: '0', subTitle: ')', keyCode: 48 },
    { title: '-', subTitle: '_', keyCode: 189 },
    { title: '=', subTitle: '+', keyCode: 187 },
    { title: '😅', subTitle: '', name: 'back', keyCode: 8 },
  ],
  [
    { title: '📑', subTitle: '', name: 'tab', keyCode: 9 },
    { title: 'Q', keyCode: 81 },
    { title: 'W', keyCode: 87 },
    { title: 'E', keyCode: 69 },
    { title: 'R', keyCode: 82 },
    { title: 'T', keyCode: 84 },
    { title: 'Y', keyCode: 89 },
    { title: 'U', keyCode: 85 },
    { title: 'I', keyCode: 73 },
    { title: 'O', keyCode: 79 },
    { title: 'P', keyCode: 80 },
    { title: '[', subTitle: '{', keyCode: 219 },
    { title: ']', subTitle: '}', keyCode: 221 },
    { title: '\\', subTitle: '|', name: 'pipe', keyCode: 220 },
  ],
  [
    { title: '🔓', subTitle: '', name: 'cap', keyCode: 20 },
    { title: 'A', keyCode: 65 },
    { title: 'S', keyCode: 83 },
    { title: 'D', keyCode: 68 },
    { title: 'F', keyCode: 70 },
    { title: 'G', keyCode: 71 },
    { title: 'H', keyCode: 72 },
    { title: 'J', keyCode: 74 },
    { title: 'K', keyCode: 75 },
    { title: 'L', keyCode: 76 },
    { title: ';', subTitle: ':', keyCode: 186 },
    { title: ',', subTitle: '"', keyCode: 222 },
    { title: '😤', subTitle: '', name: 'enter', keyCode: 13 },
  ],
  [
    { title: '💪', subTitle: '', name: 'shift', keyCode: 16 },
    { title: 'Z', keyCode: 90 },
    { title: 'X', keyCode: 88 },
    { title: 'C', keyCode: 67 },
    { title: 'V', keyCode: 86 },
    { title: 'B', keyCode: 66 },
    { title: 'N', keyCode: 78 },
    { title: 'M', keyCode: 77 },
    { title: ',', subTitle: '<', keyCode: 188 },
    { title: '.', subTitle: '>', keyCode: 190 },
    { title: '/', subTitle: '?', keyCode: 191 },
    { title: '💪', subTitle: '', name: 'shift', keyCode: 16 },
  ],
  [
    { title: '☕', name: 'ctrl-left', keyCode: 17 },
    { title: '🤩', name: 'win', keyCode: 91 },
    { title: '⭐️', name: 'alt', keyCode: 18 },
    { title: '', name: 'space', keyCode: 32 },
    { title: '⭐️', name: 'alt', keyCode: 18 },
    { title: '🌈', name: 'up', keyCode: 38 },
    { title: '👨‍💻', name: 'down', keyCode: 40 },
    { title: '☕', name: 'ctrl-right', keyCode: 17 },
  ],
];
